/* ═══════════════════════════════════════════════════════════
   NewsRiver Intelligence — Synthesis Showcase
   Tab Logic + API Integration
   ═══════════════════════════════════════════════════════════ */

// ── Config ──
const API_BASE = 'https://api.yieldcircle.app';

// ── Services for Bazaar ──
const SERVICES = [
    { icon: '🧠', name: 'Intelligence Reports', endpoint: '/api/v1/intelligence/hourly', method: 'GET', price: '$0.05', desc: 'AI-curated hourly intelligence briefs covering global crypto, macro, and DeFi events with sentiment analysis.' },
    { icon: '🔮', name: 'AskRiver AI Chat', endpoint: '/api/v1/askriver', method: 'POST', price: '$0.05', desc: 'RAG-powered AI chat with 5 autonomous tools: news search, price check, trending topics, intelligence, and web query.' },
    { icon: '🔍', name: 'Semantic Search', endpoint: '/api/v1/search/semantic', method: 'GET', price: '$0.001', desc: 'Vector similarity search across 288K+ articles using multilingual embeddings. Returns ranked results by relevance.' },
    { icon: '📰', name: 'Articles Feed', endpoint: '/api/v1/articles', method: 'GET', price: '$0.001', desc: 'Real-time article stream from 277 RSS sources across 137 countries. Filter by topic, source, region, or sentiment.' },
    { icon: '📊', name: 'Crypto Prices', endpoint: '/api/v1/prices/latest', method: 'GET', price: 'Free', desc: 'Live cryptocurrency prices from CoinGecko via Coinglass proxy. BTC, ETH, SOL, and 50+ tokens with 24h change.' },
    { icon: '📈', name: 'Trending Topics', endpoint: '/api/v1/trends', method: 'GET', price: '$0.001', desc: 'AI-detected trending topics from the last 24h of global news. See what the world is talking about right now.' },
    { icon: '📧', name: 'Email Proxy', endpoint: '/api/v1/proxy/email', method: 'POST', price: '$0.05', desc: 'Send emails via Resend integration. Perfect for agent notifications, alerts, and communications.' },
    { icon: '🔗', name: 'Web Scraper', endpoint: '/api/v1/proxy/scrape', method: 'POST', price: '$0.25', desc: 'Headless browser scraping via Browserless. Extract content from any URL for agent consumption.' },
];

// ── Timeline milestones ──
const MILESTONES = [
    { date: 'Jan 2026', title: '📡 Phase 1: RSS Ingestion Engine', desc: '100+ RSS feeds, D1 database, automated cron pipeline on Cloudflare Workers.', dot: '' },
    { date: 'Jan 2026', title: '🧠 Phase 2: AI Sentiment Pipeline', desc: 'ML-powered sentiment analysis with multilingual embeddings. Every article scored on a -1 to +1 spectrum.', dot: 'purple' },
    { date: 'Feb 2026', title: '📊 Phase 3: Intelligence Reports', desc: 'Autonomous hourly/daily intelligence briefs generated by the agent. No human in the loop.', dot: 'green' },
    { date: 'Feb 2026', title: '💳 Phase 4: x402 Micropayments', desc: 'HTTP-native payments on Base. Any agent can pay per request in USDC — no API key needed.', dot: '' },
    { date: 'Feb 2026', title: '🔮 Phase 5: AskRiver AI Chat', desc: 'RAG-powered conversational AI with 5 autonomous tools. Gemini Flash Lite + tool orchestration.', dot: 'purple' },
    { date: 'Mar 2026', title: '🤖 Phase 6: Agent Ecosystem', desc: 'ElizaOS plugin (8 actions) published to npm. ClawHub skill for one-click installation.', dot: 'green' },
    { date: 'Mar 2026', title: '🪪 Phase 7: ERC-8004 Identity', desc: 'Registered for The Synthesis hackathon. On-chain agent identity on Base Mainnet.', dot: '', link: 'https://basescan.org/tx/0x6ea9aa3d963a805becab2453b590e7eaf4908a263c840641978827ce02d2c248' },
];

// ── Endpoint configs for terminal ──
const ENDPOINTS = {
    articles: { method: 'GET', path: '/api/v1/articles?limit=3', dryRun: true },
    search: { method: 'GET', path: '/api/v1/search/semantic?q=bitcoin+etf&limit=3', dryRun: true },
    intel: { method: 'GET', path: '/api/v1/intelligence/hourly', dryRun: true },
    trends: { method: 'GET', path: '/api/v1/trends', dryRun: true },
    askriver: { method: 'POST', path: '/api/v1/askriver', body: { message: 'What is trending in crypto?', model: 'gemini-2.5-flash-lite' }, dryRun: true },
    health: { method: 'GET', path: '/api/v1/health', dryRun: false },
    jobs_contract: { method: 'GET', path: '/api/jobs/contract', dryRun: false },
    jobs_0: { method: 'GET', path: '/api/jobs/0', dryRun: false },
};




// ══════════════════════════════════════
// TAB NAVIGATION
// ══════════════════════════════════════
window.switchTab = function (tabId) {
    document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));

    const tab = document.getElementById(`tab-${tabId}`);
    if (tab) tab.classList.add('active');

    const btn = document.querySelector(`[data-tab="${tabId}"]`);
    if (btn) btn.classList.add('active');
};

// ── FAQ Accordion Toggle ──
window.toggleFaq = function (btn) {
    const item = btn.closest('.faq-item');
    const wasActive = item.classList.contains('active');
    // Close all others
    document.querySelectorAll('.faq-item.active').forEach(i => i.classList.remove('active'));
    // Toggle clicked
    if (!wasActive) item.classList.add('active');
};

document.querySelectorAll('.nav-tab').forEach(btn => {
    btn.addEventListener('click', () => switchTab(btn.dataset.tab));
});

// ══════════════════════════════════════
// ANIMATED COUNTERS
// ══════════════════════════════════════
function animateCounters() {
    document.querySelectorAll('.stat-value').forEach(el => {
        const target = parseInt(el.dataset.target);
        const duration = 2000;
        const start = performance.now();

        function update(now) {
            const elapsed = now - start;
            const progress = Math.min(elapsed / duration, 1);
            const eased = 1 - Math.pow(1 - progress, 3);
            el.textContent = Math.floor(target * eased).toLocaleString();
            if (progress < 1) requestAnimationFrame(update);
        }
        requestAnimationFrame(update);
    });
}

// ══════════════════════════════════════
// BAZAAR GRID
// ══════════════════════════════════════
function renderBazaar() {
    const grid = document.getElementById('bazaar-grid');
    grid.innerHTML = SERVICES.map(s => `
    <div class="bazaar-card">
      <div class="bazaar-card-header">
        <span class="bazaar-card-icon">${s.icon}</span>
        <span class="bazaar-card-price">${s.price}</span>
      </div>
      <h4><span class="bazaar-card-method ${s.method === 'GET' ? 'method-get' : 'method-post'}">${s.method}</span>${s.name}</h4>
      <p>${s.desc}</p>
      <code>${s.endpoint}</code>
    </div>
  `).join('');
}

// ══════════════════════════════════════
// ASKRIVER DEMO
// ══════════════════════════════════════
window.setQuestion = function (q) {
    document.getElementById('ask-input').value = q;
};

window.askRiver = async function () {
    const input = document.getElementById('ask-input');
    const q = input.value.trim();
    if (!q) return;

    const responseEl = document.getElementById('ask-response');
    const answerEl = document.getElementById('ask-answer');
    const proofEl = document.getElementById('ask-proof');
    const btn = document.getElementById('ask-btn');

    responseEl.classList.remove('hidden');
    proofEl.classList.add('hidden');
    answerEl.innerHTML = '<span class="loading-dots">Thinking</span>';
    btn.disabled = true;
    btn.textContent = '...';

    try {
        const ctrl = new AbortController();
        const timeoutId = setTimeout(() => ctrl.abort(), 15000);
        const res = await fetch(`${API_BASE}/api/v1/askriver`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'X-Dry-Run': 'true' },
            body: JSON.stringify({ message: q, model: 'gemini-2.5-flash-lite' }),
            signal: ctrl.signal,
        });
        clearTimeout(timeoutId);

        const data = await res.json();
        const answer = data.response || data.answer || data.message || JSON.stringify(data, null, 2);
        answerEl.textContent = answer;

        // Generate proof hash
        const encoder = new TextEncoder();
        const hashBuffer = await crypto.subtle.digest('SHA-256', encoder.encode(answer));
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

        document.getElementById('proof-hash').textContent = hashHex;
        document.getElementById('proof-time').textContent = new Date().toISOString();
        proofEl.classList.remove('hidden');
    } catch (err) {
        answerEl.innerHTML = `<div style="color:var(--red);display:flex;align-items:center;gap:8px;"><span style="font-size:1.3rem;">⚠️</span> <span>${err.name === 'AbortError' ? 'Request timed out — the API may be cold-starting. Click Ask again to retry.' : 'Connection issue — click Ask again to retry.'}</span></div>`;
    }

    btn.disabled = false;
    btn.textContent = 'Ask →';
};

// Enter key support
document.getElementById('ask-input').addEventListener('keydown', (e) => {
    if (e.key === 'Enter') askRiver();
});

// ══════════════════════════════════════
// NEWSROOM TIMELINE
// ══════════════════════════════════════
function renderTimeline() {
    const timeline = document.getElementById('timeline');
    timeline.innerHTML = MILESTONES.map(m => `
    <div class="timeline-item">
      <div class="timeline-dot ${m.dot}"></div>
      <div class="timeline-date">${m.date}</div>
      <h4>${m.title}</h4>
      <p>${m.desc}</p>
      ${m.link ? `<a href="${m.link}" target="_blank" class="timeline-link">View on-chain ↗</a>` : ''}
    </div>
  `).join('');
}

// ══════════════════════════════════════
// LIVE TERMINAL
// ══════════════════════════════════════
function getCurlCommand(key) {
    const ep = ENDPOINTS[key];
    const url = `${API_BASE}${ep.path}`;
    if (ep.method === 'POST') {
        return `$ curl -X POST "${url}" \\\n  -H "Content-Type: application/json" \\\n  -H "X-Dry-Run: true" \\\n  -d '${JSON.stringify(ep.body)}'`;
    }
    return `$ curl "${url}" \\\n  -H "X-Dry-Run: true"`;
}

// Update curl on select change
document.getElementById('endpoint-select').addEventListener('change', (e) => {
    document.getElementById('terminal-curl').textContent = getCurlCommand(e.target.value);
    document.getElementById('terminal-output').textContent = '';
    document.getElementById('terminal-separator').classList.add('hidden');
});

window.executeEndpoint = async function () {
    const key = document.getElementById('endpoint-select').value;
    const ep = ENDPOINTS[key];
    const url = `${API_BASE}${ep.path}`;
    const outputEl = document.getElementById('terminal-output');
    const sepEl = document.getElementById('terminal-separator');

    document.getElementById('terminal-curl').textContent = getCurlCommand(key);
    outputEl.textContent = 'Loading...';
    sepEl.classList.remove('hidden');

    try {
        const options = {
            method: ep.method,
            headers: { 'Content-Type': 'application/json' },
        };
        if (ep.dryRun) options.headers['X-Dry-Run'] = 'true';
        if (ep.body) options.body = JSON.stringify(ep.body);

        const res = await fetch(url, options);
        const data = await res.json();
        outputEl.textContent = JSON.stringify(data, null, 2);
    } catch (err) {
        outputEl.textContent = `Error: ${err.message}`;
    }
};

window.copyCurl = function () {
    const key = document.getElementById('endpoint-select').value;
    const cmd = getCurlCommand(key).replace('$ ', '');
    const btn = document.querySelector('[onclick="copyCurl()"]');
    try {
        if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(cmd).then(() => {
                btn.textContent = '✅ Copied!';
                setTimeout(() => btn.textContent = '📋 Copy curl', 1500);
            }).catch(() => fallbackCopy(cmd, btn));
        } else {
            fallbackCopy(cmd, btn);
        }
    } catch (e) {
        fallbackCopy(cmd, btn);
    }
};

function fallbackCopy(text, btn) {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.cssText = 'position:fixed;left:-9999px';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    btn.textContent = '✅ Copied!';
    setTimeout(() => btn.textContent = '📋 Copy curl', 1500);
}

// ══════════════════════════════════════
// ERC-8183 JOBS TAB
// ══════════════════════════════════════
window.loadJobs = async function () {
    const listEl = document.getElementById('jobs-list');
    const countEl = document.getElementById('jobs-count');
    const statusEl = document.getElementById('contract-status');

    if (!listEl) return;
    listEl.innerHTML = '<div class="jobs-empty">Loading...</div>';

    try {
        // Fetch contract info + jobs + intents in parallel
        const [infoRes, countRes, jobsRes, intentsRes] = await Promise.all([
            fetch(`${API_BASE}/api/jobs/contract`),
            fetch(`${API_BASE}/api/jobs/count`),
            fetch(`${API_BASE}/api/jobs?limit=10`),
            fetch(`${API_BASE}/api/jobs/intents/stats`).catch(() => null),
        ]);

        const info = await infoRes.json();
        const countData = await countRes.json();
        const jobsData = await jobsRes.json();
        const intentsData = intentsRes ? await intentsRes.json() : null;

        const isDeployed = info.address && info.address !== '0x0000000000000000000000000000000000000000';
        if (statusEl) statusEl.textContent = isDeployed ? '🟢 Deployed' : '⏳ Pending';
        if (countEl) countEl.textContent = countData.count || '0';

        let html = '';

        // ── Pipeline stats section ──
        if (intentsData) {
            const pending = (intentsData.by_status || []).find(s => s.status === 'pending')?.count || 0;
            html += `
                <div class="pipeline-section">
                    <h3 class="pipeline-title">🔄 AskRiver → ERC-8183 Pipeline</h3>
                    <div class="pipeline-flow">
                        <div class="pipeline-stage">
                            <span class="pipeline-count">${intentsData.total_intents || 0}</span>
                            <span class="pipeline-label">Queries</span>
                        </div>
                        <span class="pipeline-arrow">→</span>
                        <div class="pipeline-stage">
                            <span class="pipeline-count">${pending}</span>
                            <span class="pipeline-label">Intents</span>
                        </div>
                        <span class="pipeline-arrow">→</span>
                        <div class="pipeline-stage">
                            <span class="pipeline-count">${countData.count || 0}</span>
                            <span class="pipeline-label">On-Chain</span>
                        </div>
                    </div>
                    <p class="pipeline-desc">Every AskRiver query logs an ERC-8183 job intent. Agents autonomously create, fund, and complete on-chain jobs from intelligence queries.</p>
                </div>
            `;
        }

        // ── On-chain jobs ──
        if (jobsData.jobs && jobsData.jobs.length > 0) {
            html += jobsData.jobs.map(j => `
                <div class="job-card">
                    <div class="job-card-left">
                        <h4>Job #${j.job_id}: ${j.description || 'Untitled'}</h4>
                        <p>${j.budget_usdc ? j.budget_usdc + ' USDC' : 'No budget'} · Expires ${j.expiredAt_iso ? new Date(j.expiredAt_iso).toLocaleDateString() : '—'}</p>
                    </div>
                    <span class="job-status-badge job-status-${(j.status || 'open').toLowerCase()}">${j.status}</span>
                </div>
            `).join('');
        } else {
            // Show recent agent decisions as activity when no on-chain jobs yet
            try {
                const decRes = await fetch(`${API_BASE}/api/jobs/treasury`);
                const decData = await decRes.json();
                const decisions = decData?.autonomy?.recent_decisions || [];
                if (decisions.length > 0) {
                    html += `<div class="pipeline-section"><h3 class="pipeline-title">🤖 Recent Agent Autonomous Activity</h3></div>`;
                    html += decisions.slice(0, 5).map(d => {
                        const icon = d.decision_type === 'job_creation' ? '🎯'
                            : d.decision_type === 'budget_allocation' ? '💰'
                            : d.decision_type === 'heartbeat' ? '💤' : '🤖';
                        return `
                            <div class="job-card">
                                <div class="job-card-left">
                                    <h4>${icon} ${(d.decision_type || '').replace(/_/g, ' ')}</h4>
                                    <p>${d.reasoning || 'Autonomous decision'}${d.amount_allocated > 0 ? ` · Allocated $${d.amount_allocated.toFixed(2)} USDC` : ''}</p>
                                    <p style="font-size:0.75rem;opacity:0.5;">${d.created_at ? timeAgo(d.created_at) : ''}</p>
                                </div>
                                <span class="job-status-badge job-status-${d.status === 'executed' ? 'completed' : 'open'}">${d.status || 'logged'}</span>
                            </div>`;
                    }).join('');
                    html += `<div style="text-align:center;padding:12px;opacity:0.4;font-size:0.8rem;">Agent creates on-chain jobs when trending topics + sufficient USDC balance detected</div>`;
                } else {
                    html += `<div class="jobs-empty">${isDeployed ? 'No jobs yet — agent creates them autonomously on next cron cycle.' : 'Contract deployment pending.'}</div>`;
                }
            } catch {
                html += `<div class="jobs-empty">${isDeployed ? 'No jobs yet — agent creates them autonomously on next cron cycle.' : 'Contract deployment pending.'}</div>`;
            }
        }

        listEl.innerHTML = html;

        // ── Agent Activity (autonomous brain) ──
        loadAgentActivity();

    } catch (err) {
        listEl.innerHTML = `<div class="jobs-empty">Could not load jobs: ${err.message}</div>`;
    }
};

// ══════════════════════════════════════
// AGENT ACTIVITY — AUTONOMOUS BRAIN
// ══════════════════════════════════════
async function loadAgentActivity() {
    const container = document.getElementById('agent-activity');
    if (!container) return;

    try {
        const res = await fetch(`${API_BASE}/api/jobs/treasury`);
        const data = await res.json();

        const { agent, treasury, autonomy } = data;

        // Format decisions
        const decisionsHtml = (autonomy.recent_decisions || []).slice(0, 5).map(d => {
            const icon = d.decision_type === 'job_creation' ? '🎯'
                : d.decision_type === 'budget_allocation' ? '💰'
                    : d.decision_type === 'heartbeat' ? '💤'
                        : '🤖';
            const statusCls = d.status === 'logged' ? 'decision-active'
                : d.status === 'skipped' ? 'decision-skipped'
                    : 'decision-pending';
            const ago = timeAgo(d.created_at);
            return `
                <div class="decision-card ${statusCls}">
                    <div class="decision-header">
                        <span class="decision-icon">${icon}</span>
                        <span class="decision-type">${d.decision_type.replace('_', ' ')}</span>
                        <span class="decision-time">${ago}</span>
                    </div>
                    ${d.topic ? `<div class="decision-topic">"${d.topic}"</div>` : ''}
                    <div class="decision-reasoning">${d.reasoning}</div>
                    ${d.amount_allocated > 0 ? `<div class="decision-amount">Allocated: $${d.amount_allocated.toFixed(2)} USDC</div>` : ''}
                </div>
            `;
        }).join('') || '<div class="jobs-empty">No decisions yet — agent will start on next cron cycle</div>';

        // Revenue bar width (max 100%)
        const maxBar = Math.max(treasury.balance_usdc, treasury.total_allocated, 1);
        const balPct = Math.min((treasury.balance_usdc / maxBar) * 100, 100);
        const spentPct = Math.min((treasury.total_allocated / maxBar) * 100, 100);

        container.innerHTML = `
            <div class="agent-brain-section">
                <h3 class="pipeline-title">🧠 Autonomous Agent Brain</h3>

                <div class="agent-identity-row">
                    <div class="agent-identity-card">
                        <span class="agent-status-dot"></span>
                        <div>
                            <div class="agent-name">${agent.name}</div>
                            <div class="agent-wallet-addr">${agent.wallet.slice(0, 6)}...${agent.wallet.slice(-4)}</div>
                        </div>
                        <span class="agent-badge">${agent.identity}</span>
                    </div>
                </div>

                <div class="treasury-stats">
                    <div class="treasury-stat">
                        <span class="treasury-stat-value">$${treasury.balance_usdc.toFixed(2)}</span>
                        <span class="treasury-stat-label">USDC Balance</span>
                        <div class="treasury-bar"><div class="treasury-bar-fill balance-fill" style="width:${balPct}%"></div></div>
                    </div>
                    <div class="treasury-stat">
                        <span class="treasury-stat-value">$${treasury.estimated_24h_revenue.toFixed(4)}</span>
                        <span class="treasury-stat-label">24h Revenue</span>
                    </div>
                    <div class="treasury-stat">
                        <span class="treasury-stat-value">$${treasury.total_allocated.toFixed(2)}</span>
                        <span class="treasury-stat-label">Allocated</span>
                        <div class="treasury-bar"><div class="treasury-bar-fill spent-fill" style="width:${spentPct}%"></div></div>
                    </div>
                    <div class="treasury-stat">
                        <span class="treasury-stat-value">${autonomy.total_decisions}</span>
                        <span class="treasury-stat-label">Decisions Made</span>
                    </div>
                </div>

                <h4 class="decisions-title">Recent Autonomous Decisions</h4>
                <div class="decisions-list">
                    ${decisionsHtml}
                </div>

                <div class="agent-loop-info">
                    <span>⏰ Loop interval: ${autonomy.loop_interval}</span>
                    <span>🔒 Min balance: $${autonomy.min_balance_threshold.toFixed(2)} USDC</span>
                </div>
            </div>
        `;
    } catch (err) {
        container.innerHTML = '<div class="jobs-empty">Agent activity unavailable</div>';
    }
}

function timeAgo(dateStr) {
    const now = new Date();
    const date = new Date(dateStr + 'Z'); // D1 stores UTC
    const diff = Math.floor((now - date) / 1000);
    if (diff < 60) return 'just now';
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    return `${Math.floor(diff / 86400)}d ago`;
}

function compactNum(n) {
    if (n >= 1e6) return (n / 1e6).toFixed(1) + 'M';
    if (n >= 1e3) return (n / 1e3).toFixed(1) + 'K';
    return String(n);
}

// ══════════════════════════════════════
// ANALYTICS DASHBOARD
// ══════════════════════════════════════
let analyticsInterval = null;
let analyticsLoaded = false;

window.loadAnalytics = async function () {
    const pulseMeta = document.getElementById('pulse-meta');
    if (pulseMeta) pulseMeta.textContent = 'Fetching...';

    try {
        // Parallel-fetch all endpoints (using public analytics instead of admin-gated)
        const [treasuryRes, publicAnalyticsRes, intentsRes, fleetRes, countRes] = await Promise.all([
            fetch(`${API_BASE}/api/jobs/treasury`).catch(() => null),
            fetch(`${API_BASE}/api/analytics/public?days=30`).catch(() => null),
            fetch(`${API_BASE}/api/jobs/intents/stats`).catch(() => null),
            fetch(`${API_BASE}/api/agents/fleet/stats`).catch(() => null),
            fetch(`${API_BASE}/api/jobs/count`).catch(() => null),
        ]);

        const treasury = treasuryRes ? await treasuryRes.json() : null;
        const publicAnalytics = publicAnalyticsRes ? await publicAnalyticsRes.json() : null;
        // Map public analytics to the shapes expected by the rest of the code
        const summary = publicAnalytics;
        const realtime = publicAnalytics ? { last_hour: publicAnalytics.last_hour } : null;
        const intents = intentsRes ? await intentsRes.json() : null;
        const fleet = fleetRes ? await fleetRes.json() : null;
        const jobCount = countRes ? await countRes.json() : null;

        // ── Pulse Bar (real-time) ──
        if (realtime) {
            const el = (id, v) => { const e = document.getElementById(id); if (e) e.textContent = v; };
            el('pulse-requests', compactNum(realtime.last_hour?.total_requests || 0));
            el('pulse-tokens', compactNum(realtime.last_hour?.total_tokens || 0));
            el('pulse-cost', '$' + (realtime.last_hour?.total_cost || 0).toFixed(4));
            if (pulseMeta) pulseMeta.textContent = `Updated ${new Date().toLocaleTimeString()}`;
        } else {
            if (pulseMeta) pulseMeta.textContent = 'Connected';
        }

        // ── Treasury Panel ──
        if (treasury) {
            const t = treasury.treasury || {};
            const a = treasury.autonomy || {};
            const el = (id, v) => { const e = document.getElementById(id); if (e) e.textContent = v; };
            const bal = t.balance_usdc || 0;
            const alloc = t.total_allocated || 0;
            const maxBar = Math.max(bal, alloc, 1);

            el('treasury-balance', '$' + bal.toFixed(2));
            el('treasury-revenue', '$' + (t.estimated_24h_revenue || 0).toFixed(4));
            el('treasury-allocated', '$' + alloc.toFixed(2));
            el('treasury-decisions', a.total_decisions || 0);

            const balBar = document.getElementById('treasury-balance-bar');
            const spentBar = document.getElementById('treasury-spent-bar');
            if (balBar) balBar.style.width = Math.min((bal / maxBar) * 100, 100) + '%';
            if (spentBar) spentBar.style.width = Math.min((alloc / maxBar) * 100, 100) + '%';
        }

        // ── P&L Panel ──
        if (summary) {
            const el = (id, v) => { const e = document.getElementById(id); if (e) e.textContent = v; };
            const rev = summary.totals?.revenue || 0;
            const cost = summary.totals?.cost || 0;
            const net = rev - cost;

            el('pnl-revenue', '$' + rev.toFixed(4));
            el('pnl-costs', '$' + cost.toFixed(4));
            el('pnl-net', (net >= 0 ? '+' : '') + '$' + net.toFixed(4));
            el('pnl-paid-requests', compactNum(summary.totals?.paid_requests || 0));
            el('pnl-period', `${summary.period_days || 30} days`);

            // Color net P&L
            const netEl = document.getElementById('pnl-net');
            if (netEl) {
                netEl.classList.remove('pnl-positive', 'pnl-negative');
                netEl.classList.add(net >= 0 ? 'pnl-positive' : 'pnl-negative');
            }
        }

        // ── Intelligence Pipeline ──
        if (intents || jobCount) {
            const el = (id, v) => { const e = document.getElementById(id); if (e) e.textContent = v; };
            const totalIntents = intents?.total_intents || 0;
            const onChain = jobCount?.count || 0;
            const paidReqs = treasury?.treasury?.paid_requests || summary?.totals?.paid_requests || 0;

            el('funnel-queries', compactNum(paidReqs));
            el('funnel-intents', compactNum(totalIntents));
            el('funnel-onchain', onChain);

            // Animate funnel bar widths
            const maxFunnel = Math.max(277, 288000, paidReqs, totalIntents, onChain, 1);
            const funnelBars = document.querySelectorAll('#pipeline-funnel .funnel-bar');
            const widths = [100, 85, Math.max((paidReqs / 300) * 40, 5), Math.max((totalIntents / 100) * 20, 4), Math.max((onChain / 10) * 8, 2)];
            funnelBars.forEach((bar, i) => {
                if (widths[i] !== undefined) bar.style.width = widths[i] + '%';
            });
        }

        // ── Fleet Overview ──
        if (fleet) {
            const el = (id, v) => { const e = document.getElementById(id); if (e) e.textContent = v; };
            el('fleet-buys', fleet.signals?.buys || 0);
            el('fleet-holds', fleet.signals?.holds || 0);
            el('fleet-sells', fleet.signals?.sells || 0);
            el('fleet-total-signals', fleet.signals?.total || 0);
            el('fleet-open', fleet.open_positions?.count || 0);
            const unrealized = fleet.open_positions?.unrealized_pnl || 0;
            el('fleet-unrealized', (unrealized >= 0 ? '+' : '') + '$' + Math.abs(unrealized).toFixed(2));
            const unrealizedEl = document.getElementById('fleet-unrealized');
            if (unrealizedEl) unrealizedEl.style.color = unrealized >= 0 ? '#34d399' : '#f87171';
        }

        // ── Decision Feed ──
        if (treasury?.autonomy?.recent_decisions) {
            const decisions = treasury.autonomy.recent_decisions;
            const feed = document.getElementById('decision-feed');
            const badge = document.getElementById('decision-count-badge');

            if (badge) badge.textContent = `${treasury.autonomy.total_decisions || decisions.length} decisions`;

            if (feed && decisions.length > 0) {
                feed.innerHTML = decisions.map(d => {
                    const icon = d.decision_type === 'job_creation' ? '🎯'
                        : d.decision_type === 'budget_allocation' ? '💰'
                            : d.decision_type === 'heartbeat' ? '💤' : '🤖';
                    return `
                        <div class="decision-feed-item">
                            <div class="decision-feed-icon">${icon}</div>
                            <div class="decision-feed-content">
                                <span class="decision-feed-type">${(d.decision_type || '').replace(/_/g, ' ')}</span>
                                <span class="decision-feed-time">${timeAgo(d.created_at)}</span>
                                ${d.topic ? `<div class="decision-feed-topic">"${d.topic}"</div>` : ''}
                                <div class="decision-feed-reasoning">${d.reasoning || ''}</div>
                                ${d.amount_allocated > 0 ? `<div class="decision-feed-amount">Allocated: $${d.amount_allocated.toFixed(2)} USDC</div>` : ''}
                            </div>
                        </div>
                    `;
                }).join('');
            } else if (feed) {
                feed.innerHTML = '<div class="decision-feed-empty">No decisions yet — agent will start on next cron cycle</div>';
            }
        }

        analyticsLoaded = true;

    } catch (err) {
        console.error('Analytics load error:', err);
        if (pulseMeta) pulseMeta.textContent = 'Error loading';
    }
};

// Auto-refresh logic
function startAnalyticsRefresh() {
    if (analyticsInterval) return;
    analyticsInterval = setInterval(() => {
        const tab = document.getElementById('tab-analytics');
        if (tab && tab.classList.contains('active')) {
            loadAnalytics();
        }
    }, 30000);
}

function stopAnalyticsRefresh() {
    if (analyticsInterval) {
        clearInterval(analyticsInterval);
        analyticsInterval = null;
    }
}

// ══════════════════════════════════════
// ON-CHAIN DASHBOARD (viem + API)
// ══════════════════════════════════════

const OC_CONTRACT = '0xf24225e6bcd8805c3664b3ffe84da8ba610dfca2';
const OC_USDC = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const OC_AGENT = '0xEae03EB54eB26B38057544895E834aF42fc46A69';
const OC_RPC = 'https://mainnet.base.org';
const OC_RPC_BACKUP = 'https://base.blockpi.network/v1/rpc/public';
const OC_STATUS_LABELS = ['Open', 'Funded', 'Submitted', 'Completed', 'Rejected', 'Expired'];
const OC_STATUS_COLORS = { Open: '#3b82f6', Funded: '#f59e0b', Submitted: '#8b5cf6', Completed: '#10b981', Rejected: '#ef4444', Expired: '#6b7280' };

let onchainLoaded = false;

// ── Minimal eth_call helpers with failover ──
async function ethCall(to, data) {
    const rpcs = [OC_RPC, OC_RPC_BACKUP];
    for (const rpc of rpcs) {
        try {
            const res = await fetch(rpc, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'eth_call', params: [{ to, data }, 'latest'] })
            });
            if (!res.ok) continue;
            const json = await res.json();
            if (json.error) continue;
            return json.result;
        } catch { continue; }
    }
    return '0x';
}

async function ocGetJobCount() {
    try {
        // getJobCount() selector = 0xb02b4a2f
        const result = await ethCall(OC_CONTRACT, '0xb02b4a2f');
        return parseInt(result, 16);
    } catch { return 0; }
}

async function ocGetUsdcBalance() {
    try {
        // balanceOf(address) selector = 0x70a08231, padded address
        const paddedAddr = '000000000000000000000000' + OC_AGENT.slice(2).toLowerCase();
        const result = await ethCall(OC_USDC, '0x70a08231' + paddedAddr);
        return parseInt(result, 16) / 1e6;
    } catch { return 0; }
}

async function ocGetJob(jobId) {
    try {
        // getJob(uint256) selector = 0xbf22c457 — pad uint256
        const paddedId = jobId.toString(16).padStart(64, '0');
        const result = await ethCall(OC_CONTRACT, '0xbf22c457' + paddedId);
        if (!result || result === '0x' || result.length < 130) return null;
        // ABI: returns (tuple(client, provider, evaluator, hook, string description, uint256 budget, uint256 expiredAt, uint8 status, bytes32 deliverable))
        // word[0] = offset pointer to tuple data (0x20) — SKIP THIS
        // word[1] = client, word[2] = provider, word[3] = evaluator, word[4] = hook
        // word[5] = offset to description string (relative to tuple start at word[1])
        // word[6] = budget, word[7] = expiredAt, word[8] = status, word[9] = deliverable
        const hex = result.slice(2);
        const word = (i) => hex.slice(i * 64, (i + 1) * 64);
        const addr = (i) => '0x' + word(i).slice(24);
        const num = (i) => parseInt(word(i), 16);

        const BASE = 1; // skip word[0] (tuple offset pointer)
        const client = addr(BASE + 0);
        const provider = addr(BASE + 1);
        const evaluator = addr(BASE + 2);
        const hook = addr(BASE + 3);
        const budget = num(BASE + 5) / 1e6;
        const expiredAt = num(BASE + 6);
        const statusCode = num(BASE + 7);
        const status = OC_STATUS_LABELS[statusCode] || 'Unknown';

        // Decode dynamic string (description)
        const descOffsetBytes = num(BASE + 4); // offset relative to tuple start
        const descWordIdx = BASE + (descOffsetBytes / 32);
        const descLen = parseInt(hex.slice(descWordIdx * 64, (descWordIdx + 1) * 64), 16);
        let description = '';
        try {
            const descHex = hex.slice((descWordIdx + 1) * 64, (descWordIdx + 1) * 64 + descLen * 2);
            description = new TextDecoder().decode(new Uint8Array(descHex.match(/.{2}/g).map(b => parseInt(b, 16))));
        } catch { description = 'On-chain job #' + jobId; }

        return { id: jobId, client, provider, evaluator, budget, status, description, expiredAt };
    } catch (e) { console.warn('getJob error:', e); return null; }
}

function shortenAddr(a) { return a ? `${a.slice(0, 6)}…${a.slice(-4)}` : '—'; }

window.loadOnChainData = async function () {
    const setEl = (id, v) => { const e = document.getElementById(id); if (e) e.textContent = v; };

    try {
        // 1. On-chain reads (parallel)
        const [jobCount, balance] = await Promise.all([ ocGetJobCount(), ocGetUsdcBalance() ]);
        setEl('oc-job-count', jobCount);
        setEl('oc-usdc-balance', '$' + balance.toFixed(2));
        setEl('oc-treasury-balance', '$' + balance.toFixed(4) + ' USDC');

        // 2. API calls (parallel)
        const [treasuryRes, activityRes] = await Promise.allSettled([
            fetch(`${API_BASE}/api/jobs/treasury`).then(r => r.json()),
            fetch(`${API_BASE}/api/activity`).then(r => r.json()).catch(() => null),
        ]);

        const treasury = treasuryRes.status === 'fulfilled' ? treasuryRes.value : null;
        const activity = activityRes.status === 'fulfilled' ? activityRes.value : null;

        // Treasury
        if (treasury?.treasury) {
            const t = treasury.treasury;
            setEl('oc-treasury-revenue', '$' + (t.total_revenue || 0).toFixed(4));
            setEl('oc-decisions', treasury.autonomy?.total_decisions || 0);
            setEl('oc-paid-requests', compactNum(t.paid_requests || 0));
        }

        // 3. Load on-chain jobs
        const jobsList = document.getElementById('oc-jobs-list');
        if (jobCount > 0 && jobsList) {
            const jobs = [];
            const limit = Math.min(jobCount, 10);
            for (let i = 0; i < limit; i++) {
                const job = await ocGetJob(i);
                if (job) jobs.push(job);
            }
            if (jobs.length > 0) {
                jobsList.innerHTML = jobs.map(j => `
                    <div class="oc-job-row">
                        <div class="oc-job-header">
                            <span class="oc-job-id">#${j.id}</span>
                            <span class="oc-job-status" style="background:${OC_STATUS_COLORS[j.status] || '#6b7280'}20;color:${OC_STATUS_COLORS[j.status] || '#6b7280'}">${j.status}</span>
                        </div>
                        <div class="oc-job-desc">${j.description}</div>
                        <div class="oc-job-meta">
                            <span>💰 ${j.budget.toFixed(2)} USDC</span>
                            <span>Client: ${shortenAddr(j.client)}</span>
                            <span>Provider: ${shortenAddr(j.provider)}</span>
                        </div>
                    </div>
                `).join('');
            } else {
                jobsList.innerHTML = '<div class="oc-empty">No decodable jobs found on-chain</div>';
            }
        } else if (jobsList) {
            // Try API fallback for demo jobs
            try {
                const apiJobs = await fetch(`${API_BASE}/api/jobs`).then(r => r.json());
                if (apiJobs?.jobs?.length > 0) {
                    jobsList.innerHTML = apiJobs.jobs.map(j => `
                        <div class="oc-job-row">
                            <div class="oc-job-header">
                                <span class="oc-job-id">#${j.job_id ?? j.id}</span>
                                <span class="oc-job-status" style="background:${OC_STATUS_COLORS[j.status] || '#6b7280'}20;color:${OC_STATUS_COLORS[j.status] || '#6b7280'}">${j.status || 'Completed'}</span>
                            </div>
                            <div class="oc-job-desc">${j.description || j.topic || 'Intelligence job'}</div>
                            <div class="oc-job-meta">
                                <span>💰 ${(j.budget || j.amount_allocated || 0).toFixed ? (j.budget || j.amount_allocated || 0).toFixed(2) : j.budget || '0'} USDC</span>
                                ${j.tx_hash ? `<a href="https://basescan.org/tx/${j.tx_hash}" target="_blank" style="color:var(--accent)">View TX ↗</a>` : ''}
                            </div>
                        </div>
                    `).join('');
                } else {
                    jobsList.innerHTML = '<div class="oc-empty">No jobs found — autonomous loop will create jobs when budget is available</div>';
                }
            } catch {
                jobsList.innerHTML = '<div class="oc-empty">No jobs yet — contract deployment pending</div>';
            }
        }

        // 4. Activity feed
        const activityFeed = document.getElementById('oc-activity-feed');
        if (activityFeed) {
            const events = activity?.events || activity?.activity || [];
            if (events.length > 0) {
                activityFeed.innerHTML = events.slice(0, 15).map(e => `
                    <div class="oc-activity-item">
                        <span class="oc-activity-icon">${e.type === 'job_created' ? '📝' : e.type === 'payment' ? '💸' : e.type === 'query' ? '🔍' : '⚡'}</span>
                        <div class="oc-activity-content">
                            <span class="oc-activity-type">${(e.type || '').replace(/_/g, ' ')}</span>
                            <span class="oc-activity-desc">${e.description || e.topic || ''}</span>
                        </div>
                        <span class="oc-activity-time">${e.created_at ? timeAgo(e.created_at) : ''}</span>
                    </div>
                `).join('');
            } else {
                activityFeed.innerHTML = '<div class="oc-empty">No recent activity — agent monitors continuously</div>';
            }
        }

        onchainLoaded = true;
    } catch (err) {
        console.error('On-chain data load error:', err);
    }
};

// ══════════════════════════════════════
// INIT
// ══════════════════════════════════════
document.addEventListener('DOMContentLoaded', () => {
    // Three.js removed — using CSS dot-grid background
    animateCounters();
    renderBazaar();
    renderTimeline();

    // Set initial curl
    document.getElementById('terminal-curl').textContent = getCurlCommand('articles');

    // Load ERC-8183 jobs tab data
    loadJobs();
});

// ── Hook analytics + on-chain into tab switch ──
const _origSwitchTab = window.switchTab;
window.switchTab = function (tabId) {
    _origSwitchTab(tabId);
    if (tabId === 'analytics') {
        if (!analyticsLoaded) loadAnalytics();
        startAnalyticsRefresh();
    } else if (tabId === 'onchain') {
        if (!onchainLoaded) loadOnChainData();
    } else {
        stopAnalyticsRefresh();
    }
};

// ══════════════════════════════════════
// BRIDGE TAB — Live Quote Fetcher
// ══════════════════════════════════════

window.fetchBridgeQuote = async function () {
    const btn = document.getElementById('bridge-quote-btn');
    const result = document.getElementById('bridge-result');
    const from = document.getElementById('bridge-from').value;
    const to = document.getElementById('bridge-to').value;
    const token = document.getElementById('bridge-token').value;
    const amount = document.getElementById('bridge-amount').value;

    if (from === to) {
        result.style.display = 'block';
        result.innerHTML = '<div style="color:#f87171;text-align:center;">⚠️ Origin and destination chains must be different</div>';
        return;
    }

    btn.disabled = true;
    btn.textContent = 'Querying solvers...';
    result.style.display = 'block';
    result.innerHTML = '<div style="text-align:center;color:rgba(255,255,255,0.5);">🔄 Fetching live quote from Across solver network...</div>';

    try {
        const ctrl = new AbortController();
        const timeoutId = setTimeout(() => ctrl.abort(), 15000);
        const res = await fetch(
            `${API_BASE}/api/bridge/quote?from=${from}&to=${to}&token=${token}&amount=${amount}`,
            { signal: ctrl.signal }
        );
        clearTimeout(timeoutId);
        const data = await res.json();

        if (data.error) {
            result.innerHTML = `<div style="color:#f87171;text-align:center;">⚠️ ${data.error}</div>`;
            return;
        }

        const q = data.quote;
        const chainNames = { '1': 'Ethereum', '8453': 'Base', '42161': 'Arbitrum', '10': 'Optimism', '137': 'Polygon' };
        result.innerHTML = `
            <div class="bridge-result-grid">
                <div class="bridge-result-item">
                    <div class="label">Route</div>
                    <div class="value">${chainNames[from] || from} → ${chainNames[to] || to}</div>
                </div>
                <div class="bridge-result-item">
                    <div class="label">Fill Time</div>
                    <div class="value highlight">${q.estimatedFillTime}</div>
                </div>
                <div class="bridge-result-item">
                    <div class="label">You Send</div>
                    <div class="value">${q.inputAmount.human} ${q.inputToken.symbol}</div>
                </div>
                <div class="bridge-result-item">
                    <div class="label">You Receive</div>
                    <div class="value highlight">${q.outputAmount.human} ${q.outputToken?.symbol || q.inputToken.symbol}</div>
                </div>
                <div class="bridge-result-item">
                    <div class="label">Total Fee</div>
                    <div class="value">${q.fees.total.human} (${q.fees.total.pct})</div>
                </div>
                <div class="bridge-result-item">
                    <div class="label">Platform Fee</div>
                    <div class="value">${q.fees.platform.human} (${q.fees.platform.bps} bps)</div>
                </div>
                <div class="bridge-result-item">
                    <div class="label">Solver</div>
                    <div class="value" style="font-size:0.75rem;word-break:break-all;">${q.exclusiveRelayer || 'Open market'}</div>
                </div>
                <div class="bridge-result-item">
                    <div class="label">Quote ID</div>
                    <div class="value" style="font-size:0.75rem;">${q.quoteId || ''}</div>
                </div>
            </div>
            <div style="text-align:center;margin-top:16px;font-size:0.75rem;color:rgba(255,255,255,0.3);">
                ✅ Live data from Across Protocol solver network · ${new Date().toLocaleTimeString()}
            </div>`;
    } catch (err) {
        result.innerHTML = `<div style="color:#f87171;text-align:center;">⚠️ ${err.name === 'AbortError' ? 'Request timed out — the bridge solver may be busy. Click "Get Live Quote" to retry.' : 'Connection issue — click "Get Live Quote" to retry.'}</div>`;
    } finally {
        btn.disabled = false;
        btn.textContent = 'Get Live Quote →';
    }
};

window.swapBridgeChains = function () {
    const from = document.getElementById('bridge-from');
    const to = document.getElementById('bridge-to');
    const tmp = from.value;
    from.value = to.value;
    to.value = tmp;
};

// ── Code Tab Switching (Bridge) ──
document.querySelectorAll('.code-tab[data-codetab]').forEach(tab => {
    tab.addEventListener('click', () => {
        tab.closest('.section-container').querySelectorAll('.code-tab[data-codetab]').forEach(t => t.classList.remove('active'));
        tab.closest('.section-container').querySelectorAll('[id^="codetab-"]').forEach(p => p.classList.remove('active'));
        tab.classList.add('active');
        document.getElementById(`codetab-${tab.dataset.codetab}`).classList.add('active');
    });
});

// ── Code Tab Switching (DeFi) ──
document.querySelectorAll('.code-tab[data-defitab]').forEach(tab => {
    tab.addEventListener('click', () => {
        tab.closest('.section-container').querySelectorAll('.code-tab[data-defitab]').forEach(t => t.classList.remove('active'));
        tab.closest('.section-container').querySelectorAll('[id^="defitab-"]').forEach(p => p.classList.remove('active'));
        tab.classList.add('active');
        document.getElementById(`defitab-${tab.dataset.defitab}`).classList.add('active');
    });
});

// ── DeFi Capability Pill Highlight ──
document.querySelectorAll('.pill-bar .pill').forEach(pill => {
    pill.addEventListener('click', () => {
        pill.closest('.pill-bar').querySelectorAll('.pill').forEach(p => p.classList.remove('active'));
        pill.classList.add('active');
    });
});
