/* ═══════════════════════════════════════════════════════════
   NewsRiver Intelligence — Synthesis Showcase
   Three.js 3D Agent Viz + Tab Logic + API Integration
   ═══════════════════════════════════════════════════════════ */

import * as THREE from 'three';

// ── Config ──
const API_BASE = 'https://api.yieldcircle.app';

// ── Services for Bazaar ──
const SERVICES = [
    { icon: '🧠', name: 'Intelligence Reports', endpoint: '/api/v1/intelligence/hourly', method: 'GET', price: '$0.05', desc: 'AI-curated hourly intelligence briefs covering global crypto, macro, and DeFi events with sentiment analysis.' },
    { icon: '🔮', name: 'AskRiver AI Chat', endpoint: '/api/v1/askriver', method: 'POST', price: '$0.05', desc: 'RAG-powered AI chat with 5 autonomous tools: news search, price check, trending topics, intelligence, and web query.' },
    { icon: '🔍', name: 'Semantic Search', endpoint: '/api/v1/search/semantic', method: 'GET', price: '$0.001', desc: 'Vector similarity search across 288K+ articles using multilingual embeddings. Returns ranked results by relevance.' },
    { icon: '📰', name: 'Articles Feed', endpoint: '/api/v1/articles', method: 'GET', price: '$0.001', desc: 'Real-time article stream from 277 RSS sources across 137 countries. Filter by topic, source, region, or sentiment.' },
    { icon: '📊', name: 'Crypto Prices', endpoint: '/api/v1/prices/latest', method: 'GET', price: 'Free', desc: 'Live cryptocurrency prices from CoinGecko via Coinglass proxy. BTC, ETH, SOL, and 50+ tokens with 24h change.' },
    { icon: '📈', name: 'Trending Topics', endpoint: '/api/v1/trends', method: 'GET', price: '$0.001', desc: 'AI-detected trending topics from the last 24h of global news. See what the world is talking about right now.' },
    { icon: '📧', name: 'Email Proxy', endpoint: '/api/v1/proxy/email', method: 'POST', price: '$0.05', desc: 'Send emails via Resend integration. Perfect for agent notifications, alerts, and communications.' },
    { icon: '🔗', name: 'Web Scraper', endpoint: '/api/v1/proxy/scrape', method: 'POST', price: '$0.25', desc: 'Headless browser scraping via Browserless. Extract content from any URL for agent consumption.' },
];

// ── Timeline milestones ──
const MILESTONES = [
    { date: 'Jan 2026', title: '📡 Phase 1: RSS Ingestion Engine', desc: '100+ RSS feeds, D1 database, automated cron pipeline on Cloudflare Workers.', dot: '' },
    { date: 'Jan 2026', title: '🧠 Phase 2: AI Sentiment Pipeline', desc: 'ML-powered sentiment analysis with multilingual embeddings. Every article scored on a -1 to +1 spectrum.', dot: 'purple' },
    { date: 'Feb 2026', title: '📊 Phase 3: Intelligence Reports', desc: 'Autonomous hourly/daily intelligence briefs generated by the agent. No human in the loop.', dot: 'green' },
    { date: 'Feb 2026', title: '💳 Phase 4: x402 Micropayments', desc: 'HTTP-native payments on Base. Any agent can pay per request in USDC — no API key needed.', dot: '' },
    { date: 'Feb 2026', title: '🔮 Phase 5: AskRiver AI Chat', desc: 'RAG-powered conversational AI with 5 autonomous tools. Gemini Flash Lite + tool orchestration.', dot: 'purple' },
    { date: 'Mar 2026', title: '🤖 Phase 6: Agent Ecosystem', desc: 'ElizaOS plugin (8 actions) published to npm. ClawHub skill for one-click installation.', dot: 'green' },
    { date: 'Mar 2026', title: '🪪 Phase 7: ERC-8004 Identity', desc: 'Registered for The Synthesis hackathon. On-chain agent identity on Base Mainnet.', dot: '', link: 'https://basescan.org/tx/0x6ea9aa3d963a805becab2453b590e7eaf4908a263c840641978827ce02d2c248' },
];

// ── Endpoint configs for terminal ──
const ENDPOINTS = {
    articles: { method: 'GET', path: '/api/v1/articles?limit=3', dryRun: true },
    search: { method: 'GET', path: '/api/v1/search/semantic?q=bitcoin+etf&limit=3', dryRun: true },
    intel: { method: 'GET', path: '/api/v1/intelligence/hourly', dryRun: true },
    trends: { method: 'GET', path: '/api/v1/trends', dryRun: true },
    askriver: { method: 'POST', path: '/api/v1/askriver', body: { message: 'What is trending in crypto?', model: 'gemini-2.5-flash-lite' }, dryRun: true },
    health: { method: 'GET', path: '/api/v1/health', dryRun: false },
    jobs_contract: { method: 'GET', path: '/api/jobs/contract', dryRun: false },
    jobs_0: { method: 'GET', path: '/api/jobs/0', dryRun: false },
};

// ══════════════════════════════════════
// THREE.JS 3D AGENT VISUALIZATION
// ══════════════════════════════════════

let scene, camera, renderer, clock;
let centralOrb, subOrbs = [], particles = [];
let mouseX = 0, mouseY = 0;

function initThree() {
    const canvas = document.getElementById('three-canvas');
    scene = new THREE.Scene();
    clock = new THREE.Clock();

    camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.z = 6;

    renderer = new THREE.WebGLRenderer({ canvas, alpha: true, antialias: true });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));

    // ── Central Agent Orb ──
    const centralGeo = new THREE.SphereGeometry(0.8, 64, 64);
    const centralMat = new THREE.MeshPhongMaterial({
        color: 0x00f0ff,
        emissive: 0x003040,
        shininess: 100,
        transparent: true,
        opacity: 0.85,
    });
    centralOrb = new THREE.Mesh(centralGeo, centralMat);
    scene.add(centralOrb);

    // Central glow
    const glowGeo = new THREE.SphereGeometry(1.1, 32, 32);
    const glowMat = new THREE.MeshBasicMaterial({
        color: 0x00f0ff,
        transparent: true,
        opacity: 0.08,
    });
    const glow = new THREE.Mesh(glowGeo, glowMat);
    centralOrb.add(glow);

    // ── Sub-Agent Orbs ──
    const subAgents = [
        { color: 0x10b981, emissive: 0x052e21, name: 'Harvester', offset: 0 },
        { color: 0x8b5cf6, emissive: 0x1a0a3e, name: 'ML Pipeline', offset: Math.PI / 2 },
        { color: 0xf59e0b, emissive: 0x3d2605, name: 'Crypto Engine', offset: Math.PI },
        { color: 0xef4444, emissive: 0x3d0c0c, name: 'Executor', offset: (3 * Math.PI) / 2 },
    ];

    subAgents.forEach((agent) => {
        const geo = new THREE.SphereGeometry(0.3, 32, 32);
        const mat = new THREE.MeshPhongMaterial({
            color: agent.color,
            emissive: agent.emissive,
            shininess: 80,
            transparent: true,
            opacity: 0.9,
        });
        const mesh = new THREE.Mesh(geo, mat);

        // Add subtle glow
        const subGlow = new THREE.Mesh(
            new THREE.SphereGeometry(0.42, 16, 16),
            new THREE.MeshBasicMaterial({ color: agent.color, transparent: true, opacity: 0.06 })
        );
        mesh.add(subGlow);

        mesh.userData = { angle: agent.offset, radius: 2.8, speed: 0.3 + Math.random() * 0.15, yOffset: (Math.random() - 0.5) * 0.8 };
        scene.add(mesh);
        subOrbs.push(mesh);
    });

    // ── Particle System (data streams) ──
    const particleCount = 800;
    const particleGeo = new THREE.BufferGeometry();
    const positions = new Float32Array(particleCount * 3);
    const colors = new Float32Array(particleCount * 3);

    for (let i = 0; i < particleCount; i++) {
        const theta = Math.random() * Math.PI * 2;
        const phi = Math.random() * Math.PI;
        const r = 1.5 + Math.random() * 3;
        positions[i * 3] = r * Math.sin(phi) * Math.cos(theta);
        positions[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta) * 0.6;
        positions[i * 3 + 2] = r * Math.cos(phi);

        const c = new THREE.Color().setHSL(0.5 + Math.random() * 0.15, 0.8, 0.6);
        colors[i * 3] = c.r;
        colors[i * 3 + 1] = c.g;
        colors[i * 3 + 2] = c.b;
    }

    particleGeo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    particleGeo.setAttribute('color', new THREE.BufferAttribute(colors, 3));

    const particleMat = new THREE.PointsMaterial({
        size: 0.03,
        vertexColors: true,
        transparent: true,
        opacity: 0.6,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
    });

    const particleSystem = new THREE.Points(particleGeo, particleMat);
    scene.add(particleSystem);
    particles.push(particleSystem);

    // ── Connection lines (orbital rings) ──
    const ringGeo = new THREE.RingGeometry(2.75, 2.85, 64);
    const ringMat = new THREE.MeshBasicMaterial({
        color: 0x00f0ff,
        transparent: true,
        opacity: 0.04,
        side: THREE.DoubleSide,
    });
    const ring = new THREE.Mesh(ringGeo, ringMat);
    ring.rotation.x = Math.PI / 2;
    scene.add(ring);

    // Second ring tilted
    const ring2 = ring.clone();
    ring2.rotation.x = Math.PI / 3;
    ring2.rotation.y = Math.PI / 4;
    ring2.material = ringMat.clone();
    ring2.material.opacity = 0.025;
    scene.add(ring2);

    // ── Lights ──
    const ambient = new THREE.AmbientLight(0x404060, 0.6);
    scene.add(ambient);

    const point1 = new THREE.PointLight(0x00f0ff, 1.2, 20);
    point1.position.set(3, 3, 3);
    scene.add(point1);

    const point2 = new THREE.PointLight(0x8b5cf6, 0.8, 20);
    point2.position.set(-3, -2, 2);
    scene.add(point2);

    // ── Mouse tracking ──
    document.addEventListener('mousemove', (e) => {
        mouseX = (e.clientX / window.innerWidth - 0.5) * 2;
        mouseY = (e.clientY / window.innerHeight - 0.5) * 2;
    });

    window.addEventListener('resize', () => {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
    });

    animate();
}

function animate() {
    requestAnimationFrame(animate);
    const t = clock.getElapsedTime();

    // Central orb gentle bob
    centralOrb.rotation.y = t * 0.15;
    centralOrb.position.y = Math.sin(t * 0.5) * 0.1;

    // Sub-orbs orbit
    subOrbs.forEach((orb) => {
        const d = orb.userData;
        d.angle += d.speed * 0.008;
        orb.position.x = Math.cos(d.angle) * d.radius;
        orb.position.z = Math.sin(d.angle) * d.radius;
        orb.position.y = d.yOffset + Math.sin(t * 0.8 + d.angle) * 0.3;
        orb.rotation.y = t * 0.3;
    });

    // Particles rotate slowly
    particles.forEach((p) => {
        p.rotation.y = t * 0.05;
        p.rotation.x = Math.sin(t * 0.02) * 0.1;
    });

    // Camera follows mouse gently
    camera.position.x += (mouseX * 0.5 - camera.position.x) * 0.03;
    camera.position.y += (-mouseY * 0.3 - camera.position.y) * 0.03;
    camera.lookAt(0, 0, 0);

    renderer.render(scene, camera);
}

// ══════════════════════════════════════
// TAB NAVIGATION
// ══════════════════════════════════════
window.switchTab = function (tabId) {
    document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));

    const tab = document.getElementById(`tab-${tabId}`);
    if (tab) tab.classList.add('active');

    const btn = document.querySelector(`[data-tab="${tabId}"]`);
    if (btn) btn.classList.add('active');
};

// ── FAQ Accordion Toggle ──
window.toggleFaq = function (btn) {
    const item = btn.closest('.faq-item');
    const wasActive = item.classList.contains('active');
    // Close all others
    document.querySelectorAll('.faq-item.active').forEach(i => i.classList.remove('active'));
    // Toggle clicked
    if (!wasActive) item.classList.add('active');
};

document.querySelectorAll('.nav-tab').forEach(btn => {
    btn.addEventListener('click', () => switchTab(btn.dataset.tab));
});

// ══════════════════════════════════════
// ANIMATED COUNTERS
// ══════════════════════════════════════
function animateCounters() {
    document.querySelectorAll('.stat-value').forEach(el => {
        const target = parseInt(el.dataset.target);
        const duration = 2000;
        const start = performance.now();

        function update(now) {
            const elapsed = now - start;
            const progress = Math.min(elapsed / duration, 1);
            const eased = 1 - Math.pow(1 - progress, 3);
            el.textContent = Math.floor(target * eased).toLocaleString();
            if (progress < 1) requestAnimationFrame(update);
        }
        requestAnimationFrame(update);
    });
}

// ══════════════════════════════════════
// BAZAAR GRID
// ══════════════════════════════════════
function renderBazaar() {
    const grid = document.getElementById('bazaar-grid');
    grid.innerHTML = SERVICES.map(s => `
    <div class="bazaar-card">
      <div class="bazaar-card-header">
        <span class="bazaar-card-icon">${s.icon}</span>
        <span class="bazaar-card-price">${s.price}</span>
      </div>
      <h4><span class="bazaar-card-method ${s.method === 'GET' ? 'method-get' : 'method-post'}">${s.method}</span>${s.name}</h4>
      <p>${s.desc}</p>
      <code>${s.endpoint}</code>
    </div>
  `).join('');
}

// ══════════════════════════════════════
// ASKRIVER DEMO
// ══════════════════════════════════════
window.setQuestion = function (q) {
    document.getElementById('ask-input').value = q;
};

window.askRiver = async function () {
    const input = document.getElementById('ask-input');
    const q = input.value.trim();
    if (!q) return;

    const responseEl = document.getElementById('ask-response');
    const answerEl = document.getElementById('ask-answer');
    const proofEl = document.getElementById('ask-proof');
    const btn = document.getElementById('ask-btn');

    responseEl.classList.remove('hidden');
    proofEl.classList.add('hidden');
    answerEl.innerHTML = '<span class="loading-dots">Thinking</span>';
    btn.disabled = true;
    btn.textContent = '...';

    try {
        const res = await fetch(`${API_BASE}/api/v1/askriver`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'X-Dry-Run': 'true' },
            body: JSON.stringify({ message: q, model: 'gemini-2.5-flash-lite' }),
        });

        const data = await res.json();
        const answer = data.response || data.answer || data.message || JSON.stringify(data, null, 2);
        answerEl.textContent = answer;

        // Generate proof hash
        const encoder = new TextEncoder();
        const hashBuffer = await crypto.subtle.digest('SHA-256', encoder.encode(answer));
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

        document.getElementById('proof-hash').textContent = hashHex;
        document.getElementById('proof-time').textContent = new Date().toISOString();
        proofEl.classList.remove('hidden');
    } catch (err) {
        answerEl.textContent = `Error: ${err.message}. The API might be rate-limited or unavailable. Try again in a moment.`;
    }

    btn.disabled = false;
    btn.textContent = 'Ask →';
};

// Enter key support
document.getElementById('ask-input').addEventListener('keydown', (e) => {
    if (e.key === 'Enter') askRiver();
});

// ══════════════════════════════════════
// NEWSROOM TIMELINE
// ══════════════════════════════════════
function renderTimeline() {
    const timeline = document.getElementById('timeline');
    timeline.innerHTML = MILESTONES.map(m => `
    <div class="timeline-item">
      <div class="timeline-dot ${m.dot}"></div>
      <div class="timeline-date">${m.date}</div>
      <h4>${m.title}</h4>
      <p>${m.desc}</p>
      ${m.link ? `<a href="${m.link}" target="_blank" class="timeline-link">View on-chain ↗</a>` : ''}
    </div>
  `).join('');
}

// ══════════════════════════════════════
// LIVE TERMINAL
// ══════════════════════════════════════
function getCurlCommand(key) {
    const ep = ENDPOINTS[key];
    const url = `${API_BASE}${ep.path}`;
    if (ep.method === 'POST') {
        return `$ curl -X POST "${url}" \\\n  -H "Content-Type: application/json" \\\n  -H "X-Dry-Run: true" \\\n  -d '${JSON.stringify(ep.body)}'`;
    }
    return `$ curl "${url}" \\\n  -H "X-Dry-Run: true"`;
}

// Update curl on select change
document.getElementById('endpoint-select').addEventListener('change', (e) => {
    document.getElementById('terminal-curl').textContent = getCurlCommand(e.target.value);
    document.getElementById('terminal-output').textContent = '';
    document.getElementById('terminal-separator').classList.add('hidden');
});

window.executeEndpoint = async function () {
    const key = document.getElementById('endpoint-select').value;
    const ep = ENDPOINTS[key];
    const url = `${API_BASE}${ep.path}`;
    const outputEl = document.getElementById('terminal-output');
    const sepEl = document.getElementById('terminal-separator');

    document.getElementById('terminal-curl').textContent = getCurlCommand(key);
    outputEl.textContent = 'Loading...';
    sepEl.classList.remove('hidden');

    try {
        const options = {
            method: ep.method,
            headers: { 'Content-Type': 'application/json' },
        };
        if (ep.dryRun) options.headers['X-Dry-Run'] = 'true';
        if (ep.body) options.body = JSON.stringify(ep.body);

        const res = await fetch(url, options);
        const data = await res.json();
        outputEl.textContent = JSON.stringify(data, null, 2);
    } catch (err) {
        outputEl.textContent = `Error: ${err.message}`;
    }
};

window.copyCurl = function () {
    const key = document.getElementById('endpoint-select').value;
    const cmd = getCurlCommand(key).replace('$ ', '');
    navigator.clipboard.writeText(cmd).then(() => {
        const btn = document.querySelector('[onclick="copyCurl()"]');
        btn.textContent = '✅ Copied!';
        setTimeout(() => btn.textContent = '📋 Copy curl', 1500);
    });
};

// ══════════════════════════════════════
// ERC-8183 JOBS TAB
// ══════════════════════════════════════
window.loadJobs = async function () {
    const listEl = document.getElementById('jobs-list');
    const countEl = document.getElementById('jobs-count');
    const statusEl = document.getElementById('contract-status');

    if (!listEl) return;
    listEl.innerHTML = '<div class="jobs-empty">Loading...</div>';

    try {
        // Fetch contract info + jobs + intents in parallel
        const [infoRes, countRes, jobsRes, intentsRes] = await Promise.all([
            fetch(`${API_BASE}/api/jobs/contract`),
            fetch(`${API_BASE}/api/jobs/count`),
            fetch(`${API_BASE}/api/jobs?limit=10`),
            fetch(`${API_BASE}/api/jobs/intents/stats`).catch(() => null),
        ]);

        const info = await infoRes.json();
        const countData = await countRes.json();
        const jobsData = await jobsRes.json();
        const intentsData = intentsRes ? await intentsRes.json() : null;

        const isDeployed = info.address && info.address !== '0x0000000000000000000000000000000000000000';
        if (statusEl) statusEl.textContent = isDeployed ? '🟢 Deployed' : '⏳ Pending';
        if (countEl) countEl.textContent = countData.count || '0';

        let html = '';

        // ── Pipeline stats section ──
        if (intentsData) {
            const pending = (intentsData.by_status || []).find(s => s.status === 'pending')?.count || 0;
            html += `
                <div class="pipeline-section">
                    <h3 class="pipeline-title">🔄 AskRiver → ERC-8183 Pipeline</h3>
                    <div class="pipeline-flow">
                        <div class="pipeline-stage">
                            <span class="pipeline-count">${intentsData.total_intents || 0}</span>
                            <span class="pipeline-label">Queries</span>
                        </div>
                        <span class="pipeline-arrow">→</span>
                        <div class="pipeline-stage">
                            <span class="pipeline-count">${pending}</span>
                            <span class="pipeline-label">Intents</span>
                        </div>
                        <span class="pipeline-arrow">→</span>
                        <div class="pipeline-stage">
                            <span class="pipeline-count">${countData.count || 0}</span>
                            <span class="pipeline-label">On-Chain</span>
                        </div>
                    </div>
                    <p class="pipeline-desc">Every AskRiver query logs an ERC-8183 job intent. Agents autonomously create, fund, and complete on-chain jobs from intelligence queries.</p>
                </div>
            `;
        }

        // ── On-chain jobs ──
        if (jobsData.jobs && jobsData.jobs.length > 0) {
            html += jobsData.jobs.map(j => `
                <div class="job-card">
                    <div class="job-card-left">
                        <h4>Job #${j.job_id}: ${j.description || 'Untitled'}</h4>
                        <p>${j.budget_usdc ? j.budget_usdc + ' USDC' : 'No budget'} · Expires ${j.expiredAt_iso ? new Date(j.expiredAt_iso).toLocaleDateString() : '—'}</p>
                    </div>
                    <span class="job-status-badge job-status-${(j.status || 'open').toLowerCase()}">${j.status}</span>
                </div>
            `).join('');
        } else {
            html += `<div class="jobs-empty">${isDeployed ? 'No jobs yet — be the first to create one!' : 'Contract deployment pending.'}</div>`;
        }

        listEl.innerHTML = html;
    } catch (err) {
        listEl.innerHTML = `<div class="jobs-empty">Could not load jobs: ${err.message}</div>`;
    }
};

// ══════════════════════════════════════
// INIT
// ══════════════════════════════════════
document.addEventListener('DOMContentLoaded', () => {
    initThree();
    animateCounters();
    renderBazaar();
    renderTimeline();

    // Set initial curl
    document.getElementById('terminal-curl').textContent = getCurlCommand('articles');

    // Load ERC-8183 jobs tab data
    loadJobs();
});
